import { LocatorObject } from "./commonTypes";
export interface ILocators {
  //   poParentObject: string;
  description: string;
  locator: LocatorObject[];
}
export interface ILocatorMetadataObject {
  [key: string]: ILocators;
}

export enum LocatorTypes {
  ID = "id",
  NAME = "name",
  CLASSNAME = "className",
  XPATH = "xpath",
  CSS = "css",
  CSSSR = "css_sr",
  DEEPCSS = "deepCss", // Avoid using as deep is deprecated in most browsers and mostly this will not work
  CSSCONTAININGTEXT = "cssContainingText",
  LINKTEXT = "linkText",
  PARTIALLINKTEXT = "partialLinkText",
  BUTTONTEXT = "buttonText",
  PARTIALBUTTONTEXT = "partialButtonText",
  TAGNAME = "tagName",
  NONE = "none",
  // JS = "js",
}

export enum WAITCONDITIONS {
  NUMBEROFWINDOWSTOBE = "NUMBEROFWINDOWSTOBE",
  TEXTTOBEPRESENTINELEMENT = "TEXTTOBEPRESENTINELEMENT",
  TEXTTOBEPRESENTINELEMENTVALUE = "TEXTTOBEPRESENTINELEMENTVALUE",
  VISIBILITYOF = "VISIBILITYOF",
  ALERTISPRESENT = "ALERTISPRESENT",
  TITLECONTAINS = "TITLECONTAINS",
  TITLEIS = "TITLEIS",
  URLCONTAINS = "URLCONTAINS",
  URLIS = "URLIS",
  ELEMENTTOBECLICKABLE = "ELEMENTTOBECLICKABLE",
  ELEMENTTOBEENABLED = "ELEMENTTOBEENABLED",
  ELEMENTTOBESELECTED = "ELEMENTTOBESELECTED",
  INVISIBILITYOF = "INVISIBILITYOF",
  NUMBEROFELEMENTSTOBE = "NUMBEROFELEMENTSTOBE",
  NUMBEROFELEMENTSTOBELESSTHAN = "NUMBEROFELEMENTSTOBELESSTHAN",
  NUMBEROFELEMENTSTOBEMORETHAN = "NUMBEROFELEMENTSTOBEMORETHAN",
  PRESENCEOF = "PRESENCEOF",
  SIZEOfELEMENTTOBE = "SIZEOfELEMENTTOBE",
  STALENESSOF = "STALENESSOF",

  // Nots
  ALERTISNOTPRESENT = "ALERTISNOTPRESENT",
  TITLEDOESNOTCONTAIN = "TITLEDOESNOTCONTAIN",
  TITLEISNOT = "TITLEISNOT",
  ELEMENTNOTCLICKABLE = "ELEMENTNOTCLICKABLE",
  ABSENCEOF = "ABSENCEOF",
  TEXTNOTPRESENTINELEMENT = "TEXTNOTPRESENTINELEMENT",
  TEXTNOTPRESENTINELEMENTVALUE = "TEXTNOTPRESENTINELEMENTVALUE",
  URLDOESNOTCONTAIN = "URLDOESNOTCONTAIN",
  URLISNOT = "URLISNOT",
  NOTSTALENESSOF = "NOTSTALENESSOF",
  ELEMENTNOTSELECTED = "ELEMENTNOTSELECTED",

  // Conditions
  NOT = "NOT",
  AND = "AND",
  OR = "OR",
}
